FROM alpine:3.22

ARG DOCKER_USER=phpuser
ARG PHP_VERSION

RUN apk add --update \
    "php$PHP_VERSION" \
    "php$PHP_VERSION"-pecl-redis \
    "php$PHP_VERSION"-dom \
    "php$PHP_VERSION"-curl \
    "php$PHP_VERSION"-openssl \
    "php$PHP_VERSION"-mbstring \
    "php$PHP_VERSION"-tokenizer \
    "php$PHP_VERSION"-xml \
    "php$PHP_VERSION"-xmlwriter \
    "php$PHP_VERSION"-pcntl \
    "php$PHP_VERSION"-phar \
    "php$PHP_VERSION"-iconv \
    "php$PHP_VERSION"-apcu \
    "php$PHP_VERSION"-bcmath \
    "php$PHP_VERSION"-gmp \
    "php$PHP_VERSION"-sodium \
    "php$PHP_VERSION"-opcache \
    "php$PHP_VERSION"-json &&  \
    rm  -rf /tmp/* /var/cache/apk/* && \
    adduser -D $DOCKER_USER && \
    addgroup $DOCKER_USER www-data && \
    # Get composer
    wget https://getcomposer.org/download/2.9.8/composer.phar && \
    mv composer.phar /usr/local/bin/composer && \
    chmod +x /usr/local/bin/composer && \
    chown $DOCKER_USER:$DOCKER_USER /usr/local/bin/composer && \
    mkdir -p /var/www && \
    chown -R $DOCKER_USER:$DOCKER_USER /var/www && \
    ln -s /usr/bin/php$PHP_VERSION /usr/bin/php || true

RUN echo -e "apc.enabled=1\napc.enable_cli=1\nopcache.enable=1\nopcache.enable_cli=1\nopcache.jit=function\nopcache.jit_buffer_size=64M" >> /etc/"php$PHP_VERSION"/php.ini

USER $DOCKER_USER
WORKDIR /var/www
