name: code format
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  code-format:
    name: Code format
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.1
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          extensions: redis, pcntl

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Code format check
        run: vendor/bin/php-cs-fixer check
